logs:
  - type: 'file'
    path: './logs/'
    maxSize: '10m'
    maxFiles: '14d'
    level: 'info'
    # format: 'plain' # format of log file lines [plain or json]
    # createSymlink: false # create tailable file symlink to last log file
    # symlinkName: 'current.log' # name of tailable file
    # serviceName: '' # service name for each log line
  - type: 'console'
    level: 'info'
listen:
  host: 0.0.0.0
  port: 44123
whitelist: []
pubsubTopics: []
privateKeyFilePath: './rosenet-secret.json'
