name: Build and Push Scaling Tests Docker Images
on:
  push:
    paths:
      - packages/**
      - tests/scaling**
      - .github/workflows/scaling-test-docker-release.yml

jobs:
  build:
    strategy:
      matrix:
        role: [node, relay]
        test-name: ['', peer-discovery, pubsub, large-messages]

    name: Build and Push Scaling Test Docker Image
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rosen-bridge
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/rosen-bridge/scaling${{matrix.test-name && format('-{0}', matrix.test-name)}}-test-${{matrix.role}}
          tags: latest

      - name: Build and push ${{matrix.role}}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: tests/scaling${{matrix.test-name && format('-{0}', matrix.test-name)}}/src/${{matrix.role}}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
